import type { Metadata } from "next";
import { Inter, Great_Vibes } from "next/font/google";
import "@/styles/globals.css";
// import Footer from "@/components/layout/Footer";
// import Navbar from "@/components/layout/Navbar";
import { Toaster } from "react-hot-toast";
import LayoutWrapper from "@/components/layout/LayoutWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const great = Great_Vibes({
  variable: "--font-great",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${great.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* <Navbar /> */}
        <LayoutWrapper>
          <main className='flex-1 block'>
            {children}
            <Toaster />
          </main>
        </LayoutWrapper>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
